services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bmc_user
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: bmc_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bmc_user -d bmc_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://bmc_user:test1234@db:5432/bmc_db?schema=public
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
